export const ICONS =[
    {
        ori:"shuttle",
        sub:"bus"
    },
    {
        ori:"nosmoking",
        sub:"smoking-off"
    },
    {
        ori:"clean",
        sub:"room-service"
    },
    {
        ori:"food_and_drink",
        sub:"food"
    },
    {
        ori:"parking_sign",
        sub:"parking"
    },
    {
        ori:"family",
        sub:"human-male-female-child"
    },
    {
        ori:"pawprint",
        sub:"paw"
    },
    {
        ori:"instantconf",
        sub:"credit-card-fast-outline"
    },
    {
        ori:"videochat",
        sub:"cctv"
    },
    {
        ori:"resort",
        sub:"balcony"
    },
]